services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    env_file:
      - ../../.env
      - .env
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    external: true