#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ROOT_ENV="${REPO_ROOT}/.env"

if [[ ! -f "${ROOT_ENV}" ]]; then
    echo "Root environment file missing: ${ROOT_ENV}" >&2
    exit 1
fi

find "${REPO_ROOT}" \
    -mindepth 2 \
    -maxdepth 2 \
    -name docker-compose.yml \
    -print0 |
while IFS= read -r -d '' compose_file; do
    stack_dir="$(dirname "${compose_file}")"
    stack_name="$(basename "${stack_dir}")"

    local_env="${stack_dir}/.env"
    example_env="${stack_dir}/.env.example"
    output_env="${stack_dir}/.env.dockhand"

    # -------------------------------------------------------------------------
    # Initialize the stack's .env from .env.example if it doesn't already exist.
    # -------------------------------------------------------------------------
    if [[ ! -f "${local_env}" && -f "${example_env}" ]]; then
        cp "${example_env}" "${local_env}"
        chmod 600 "${local_env}"
        echo "Created ${stack_name}/.env from .env.example"
    fi

    {
        echo "# -------------------------------------------------------------------------"
        echo "# GENERATED FILE - DO NOT EDIT"
        echo "#"
        echo "# This file is generated by scripts/build-dockhand-envs.sh"
        echo "#"
        echo "# Sources:"
        echo "#   1. ${ROOT_ENV}"
        if [[ -f "${local_env}" ]]; then
            echo "#   2. ${local_env}"
        fi
        echo "# -------------------------------------------------------------------------"
        echo

        # Shared Eirdom configuration
        cat "${ROOT_ENV}"

        # Stack-specific overrides
        if [[ -f "${local_env}" ]]; then
            echo
            echo "# -------------------------------------------------------------------------"
            echo "# Stack-specific overrides"
            echo "# -------------------------------------------------------------------------"
            echo
            cat "${local_env}"
        fi
    } > "${output_env}"

    chmod 600 "${output_env}"
    echo "Generated ${stack_name}/.env.dockhand"
done

echo
echo "Dockhand environment generation complete."